# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install tox
      run: |
        pip install tox
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install -v
    - name: Test
      run: |
        tox
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-3.8
        path: junit/test-results-3.8.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Create Builds
      run: |
        poetry build
    - name: Upload Builds
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: dist/*

